spring.config.import=optional:file:.env[.properties]
spring.application.name=Tomato

spring.security.user.name=${SECURITY_USER:admin}
spring.security.user.password=${SECURITY_PASSWORD:admin}

spring.datasource.url=jdbc:h2:mem:tomato_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

jwt.secret=${JWT_SECRET:8w92k3n4b1l8j4g5g7k8n3h4j1k9s3b2n8g5j4k9t8n3h7f2k1s9g5n3h4j8k9}
jwt.expiration=${JWT_EXPIRATION:86400000}
frontend.url=${FRONTEND_URL:http://localhost:5173}
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
